#################################################################################################
# This is a sample deploy pipeline to enable approval process for deployments with multiple jobs
#################################################################################################

name: My Database Setup pipeline

on:
  workflow_dispatch:
    inputs:
      # Providing options for various target deployment environments
      project_code:
        description: "Project Code"
        required: true
        type: string
      
      # Optionally add other user inputs here if needed

# setting run name to know the deployment environment in the workflows history
# optionally can extend this to include version of the code deployed, release name etc.
run-name: 'Tenant Setup for Project - ${{ github.event.inputs.project_code }}'

jobs:
  setup_database_tenant:
    name: Database Tenant Setup
    runs-on: ubuntu-latest
    steps:
      - name: Create Database
        id: deploy_start
        run: |
          echo "deploy_start_time=$(date +"%Y-%m-%d %H:%M:%S")"
       ## add additional code here

  setup_orchestration_tenant:
    needs: setup_database_tenant
    name: Orchestration Tenant Setup
    runs-on: ubuntu-latest
    steps:
      - name: Create Database
        id: deploy_start
        run: |
          echo "deploy_start_time=$(date +"%Y-%m-%d %H:%M:%S")"
        ## add additional code here

  setup_etl_tool_tenant:
    needs: setup_orchestration_tenant
    name: ETL Tool Tenant Setup
    runs-on: ubuntu-latest
    steps:
      - name: Create Database
        id: deploy_start
        run: |
          echo "deploy_start_time=$(date +"%Y-%m-%d %H:%M:%S")"
        ## add additional code here

  
